// Pure composition logic - NO Node APIs (no node:fs / node:path). Browser-safe by design so the
// website's wizard (maintained outside this repo) and the CLI (scaffold.js) generate identical
// artifacts from one source.

export const PROFILES = ['backend', 'frontend', 'data-pipeline', 'llm-app'];
export const PRESETS = ['light', 'standard', 'strict'];
export const ALL_AGENTS = ['claude', 'codex', 'copilot', 'cursor', 'windsurf', 'gemini'];

// Adapter files per tool (codex/jules/aider/zed read AGENTS.md natively → no extra file).
export const AGENT_FILES = {
  claude: 'CLAUDE.md',
  copilot: '.github/copilot-instructions.md',
  cursor: '.cursor/rules/trellis.mdc',
  windsurf: '.windsurf/rules/trellis.md',
  gemini: 'GEMINI.md'
};

export const MODULES = [
  { key: 'capability_budgets', label: 'Capability budgets', hint: 'Technical + semantic anti-bloat limits, enforced.' },
  { key: 'evidence_graph', label: 'Evidence graph', hint: 'Source → Decision → Capability → Test provenance.' },
  { key: 'decision_lifecycle', label: 'Decision lifecycle (ADRs)', hint: 'Conditional decisions with review triggers.' },
  { key: 'extensions', label: 'Extension contracts', hint: 'Required registration points for plugins/providers.' },
  { key: 'tech_radar', label: 'Technology radar', hint: 'Upgrade/refactor triggers so choices do not rot.' },
  { key: 'test_cockpit', label: 'User test cockpit', hint: 'Human-verifiable expected-vs-actual surface.' }
];

export const RULES = [
  'Capability-first - every feature maps to a capability contract.',
  'Done ≠ code written - contract + examples + passing tests + human-verifiable surface + budget + current ADRs.',
  'Budgets are hard limits - fits `does` & within budget → extend; over budget → STOP, write a proposal.',
  'Obligation to NOT write code - on a stop condition, produce a split/refactor/ADR/migration proposal instead.',
  'Decisions are conditional - ADRs carry assumptions + review triggers; supersede, never delete.',
  'Evidence over confidence - back claims with a source or a test.',
  'Registration over convention - update every required extension registration point.',
  'Single source of truth - never duplicate rules across adapter files.',
  'The repository is the memory - persist decisions/sources/contracts in the repo, not in chat.'
];

const REPO_URL = 'https://github.com/e-onux/trellis';

/** Canonical AGENTS.md content for a target repo. */
export function composeAgentsMd(profile) {
  return `# AGENTS.md

> Canonical agent instructions for this repository (generated by Trellis). All other agent files are thin
> pointers to this one. Do not duplicate rules into them.

This repository follows the **Trellis** standard (profile: \`${profile}\`). Read [\`TRELLIS.md\`](./TRELLIS.md)
and \`standard/README.md\` (or ${REPO_URL}) before substantive work.

## Rules

${RULES.map((r, i) => `${i + 1}. ${r}`).join('\n')}

End substantive work with the Trellis completion report (see TRELLIS.md).
`;
}

/** Thin per-tool pointer content. `toRoot` is the relative prefix back to repo root ('./' or '../'). */
export function composeAgentPointer(key, toRoot) {
  const body = `This project uses **AGENTS.md** as the single, canonical source of agent instructions.

Read and follow [\`AGENTS.md\`](${toRoot}AGENTS.md). It references [\`TRELLIS.md\`](${toRoot}TRELLIS.md) (the
bootstrap manifesto) and the Trellis standard.

Thin pointer by design - do not duplicate rules here (Trellis rule: single source of truth).
`;
  if (key === 'cursor') return `---\ndescription: Canonical agent rules live in AGENTS.md\nalwaysApply: true\n---\n\n${body}`;
  if (key === 'windsurf') return `---\ntrigger: always_on\n---\n\n${body}`;
  return body;
}

/** Relative prefix from an adapter file back to the repo root. */
export function pointerToRoot(relPath) {
  const depth = relPath.split('/').length - 1;
  return depth === 0 ? './' : '../'.repeat(depth);
}

/** Build the .trellis.yaml config object (caller serializes to YAML). */
export function composeTrellisConfig({ profile, preset, agents, modules, profileDef }) {
  return {
    version: '0.1',
    standard: '0.1',
    profile,
    preset,
    agents: (agents || []).filter((a) => a !== 'codex'),
    modules: { ...(profileDef?.modules || {}), ...(modules || {}) },
    paths: {
      governance: 'governance', product: 'product', tech: 'tech', sources: 'sources',
      extensions: 'extensions', capabilities: 'capabilities', quality: 'quality', lifecycle: 'lifecycle'
    }
  };
}

/**
 * Minimal YAML serializer for the .trellis.yaml config shape (strings, booleans, string arrays,
 * one level of nested maps). Lets the browser emit valid YAML without a YAML dependency.
 */
export function trellisConfigToYaml(config) {
  const q = (v) => (/^[\w./-]+$/.test(String(v)) ? String(v) : JSON.stringify(String(v)));
  const lines = ['# Trellis project configuration (generated by the Trellis wizard).'];
  for (const [k, v] of Object.entries(config)) {
    if (Array.isArray(v)) {
      lines.push(`${k}:`);
      for (const item of v) lines.push(`  - ${q(item)}`);
    } else if (v && typeof v === 'object') {
      lines.push(`${k}:`);
      for (const [k2, v2] of Object.entries(v)) lines.push(`  ${k2}: ${typeof v2 === 'boolean' ? v2 : q(v2)}`);
    } else {
      lines.push(`${k}: ${typeof v === 'boolean' ? v : q(v)}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** The npx command that reproduces a given wizard selection. */
export function composeNpxCommand({ profile, preset, agents }) {
  const a = (agents && agents.length) ? ` --agents ${agents.join(',')}` : '';
  return `npx @sidrelabs/trellis init --profile ${profile} --preset ${preset}${a}`;
}

const ENABLED = (m, k) => m && m[k] !== false;

/**
 * Decide whether a repo-skeleton path belongs in the output for the chosen modules.
 * Used by the web zip builder to filter the starter tree.
 */
export function includeSkeletonPath(relPath, modules) {
  const p = relPath.replace(/\\/g, '/');
  if (!ENABLED(modules, 'evidence_graph') && p.startsWith('sources/')) return false;
  if (!ENABLED(modules, 'extensions') && p.startsWith('extensions/')) return false;
  if (!ENABLED(modules, 'tech_radar') && p === 'tech/technology-radar.yaml') return false;
  if (!ENABLED(modules, 'decision_lifecycle') && (p.startsWith('tech/decisions/') || p.startsWith('lifecycle/'))) return false;
  return true;
}

/**
 * The tailored bootstrap manifesto (the "AI spec") a user pastes into their agent.
 * Self-contained: profile/preset/modules + the rules + a condensed bootstrap procedure.
 */
export function composeBootstrap({ profile, preset, agents = [], modules = {}, projectType = 'greenfield' }) {
  const enabledModules = MODULES.filter((m) => ENABLED(modules, m.key));
  const dirs = ['governance', 'product', 'tech', 'capabilities', 'quality']
    .concat(ENABLED(modules, 'evidence_graph') ? ['sources'] : [])
    .concat(ENABLED(modules, 'extensions') ? ['extensions'] : [])
    .concat(ENABLED(modules, 'decision_lifecycle') ? ['lifecycle'] : []);
  const agentFiles = ['AGENTS.md (canonical)']
    .concat(agents.filter((a) => a !== 'codex').map((a) => AGENT_FILES[a]).filter(Boolean));
  const brownfield = projectType === 'brownfield';

  return `# TRELLIS.md - Bootstrap Manifesto (tailored)

> Generated by the Trellis wizard. Drop this file in your repo and tell your agent:
> *"Read \`TRELLIS.md\` and bootstrap this repository according to it."*
> Full standard: ${REPO_URL}

## This project
- **Profile:** \`${profile}\`
- **Preset:** \`${preset}\`${preset === 'light' ? '  (fewer enforced gates - good for brownfield)' : preset === 'strict' ? '  (all gates enforced)' : ''}
- **Project type:** ${brownfield ? 'brownfield (existing code - adopt incrementally, do NOT mass-refactor)' : 'greenfield (new)'}
- **Agent adapters to generate:** ${agentFiles.join(', ')}
- **Enabled pillars:** ${enabledModules.map((m) => m.label).join(', ')}

## What you (the agent) must do

1. ${brownfield ? 'Detect the stack WITHOUT changing code. Adopt incrementally (levels below).' : 'Detect the stack and confirm the chosen profile fits.'}
2. Scaffold these governed directories: \`${dirs.join('/  ')}/\`. Seed each with the Trellis files
   (constitution, engineering-principles, agent-authority, definition-of-done, change-policy, human-approval-policy;
   product vision/constraints/domain/terminology/non-goals; tech overview/architecture/policies${ENABLED(modules, 'tech_radar') ? '/technology-radar' : ''};
   ${ENABLED(modules, 'evidence_graph') ? 'sources MANIFEST + bibliography; ' : ''}${ENABLED(modules, 'extensions') ? 'extensions EXTENSIONS.md + registry; ' : ''}quality policies + quality-gates.yaml${ENABLED(modules, 'decision_lifecycle') ? '; lifecycle calendar + debt' : ''}).
   Write \`.trellis.yaml\` with profile=${profile}, preset=${preset}.
${ENABLED(modules, 'decision_lifecycle') ? '3. Extract each significant existing decision into an ADR (context, decision, alternatives, assumptions, consequences, review.triggers). If rationale is unknown, mark it `under-review` - do NOT invent it.\n' : ''}4. Discover meaningful capabilities. For each, create \`capabilities/<id>/contract.yaml\` with intent,
   responsibility.does/does_not, inputs, outputs, ≥1 normal + ≥1 error example, invariants, dependencies${ENABLED(modules, 'capability_budgets') ? ', budgets' : ''}, verification, review.
5. Derive contract + regression${profile === 'data-pipeline' || profile === 'llm-app' ? ' + property-based' : ''} tests from each contract.${ENABLED(modules, 'test_cockpit') ? ' Register each capability in the user test cockpit (expected vs actual).' : ''}
6. Generate the agent adapters with **AGENTS.md as canonical**; the rest are thin pointers.
7. Report anything ambiguous for human review.

## Rules you must follow

${RULES.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## Progressive adoption
L1 Governance + ADRs → L2 Capability contracts → L3 Automated tests → L4 User test cockpit →
L5 Capability & architecture budgets → L6 Lifecycle + upgrade automation.

## Completion report (always)
End substantive work with: N contracts evaluated / N passed / N need user validation /
N budget violations / N regressions / N ADRs updated / N sources added.

_Reproduce this setup with the CLI:_ \`${composeNpxCommand({ profile, preset, agents })}\`
`;
}
