// `trellis init` engine: copy the governed repo-skeleton into a target repo, apply profile/preset choices,
// and emit the agent adapter files. All artifact CONTENT comes from compose.js (shared with the web wizard);
// this module only does the Node filesystem work.
import { fs, path, findStandardDir, copyTree } from './util.js';
import { readYaml, stringifyYaml } from './yaml.js';
import {
  composeAgentsMd, composeAgentPointer, pointerToRoot, composeTrellisConfig, AGENT_FILES
} from './compose.js';

export { AGENT_FILES };

function writeAgentPointer(repoRoot, key) {
  const rel = AGENT_FILES[key];
  if (!rel) return null; // codex/jules/aider/zed read AGENTS.md natively
  const dest = path.join(repoRoot, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, composeAgentPointer(key, pointerToRoot(rel)));
  return rel;
}

/**
 * Initialize Trellis in a target repository.
 * @param {object} opts
 * @param {string} opts.repoRoot target repo
 * @param {string} [opts.profile] backend|frontend|data-pipeline|llm-app
 * @param {string} [opts.preset] light|standard|strict
 * @param {string[]} [opts.agents] adapter keys
 * @param {boolean} [opts.overwrite]
 * @param {string} [opts.standardDir]
 * @returns {{ created: string[], config: object, agents: string[] }}
 */
export function init(opts = {}) {
  const repoRoot = path.resolve(opts.repoRoot || process.cwd());
  const standardDir = opts.standardDir || findStandardDir();
  const profile = opts.profile || 'backend';
  const preset = opts.preset || 'standard';
  const agents = opts.agents || ['claude', 'codex', 'copilot', 'cursor', 'windsurf', 'gemini'];

  const profilePath = path.join(standardDir, 'profiles', `${profile}.yaml`);
  if (!fs.existsSync(profilePath)) {
    throw new Error(`Unknown profile "${profile}". Available: backend, frontend, data-pipeline, llm-app.`);
  }
  const profileDef = readYaml(profilePath);

  // 1) Copy the repo-skeleton.
  const skeleton = path.join(standardDir, 'repo-skeleton');
  const created = copyTree(skeleton, repoRoot, { overwrite: !!opts.overwrite });

  // 2) Customize .trellis.yaml from choices + profile module defaults.
  const configPath = path.join(repoRoot, '.trellis.yaml');
  const base = fs.existsSync(configPath) ? readYaml(configPath) : {};
  const config = composeTrellisConfig({ profile, preset, agents, modules: base.modules, profileDef });
  if (base.paths) config.paths = base.paths;
  fs.writeFileSync(configPath, `# Trellis project configuration (generated by \`trellis init\`).\n${stringifyYaml(config)}`);

  // 3) Emit agent adapters (AGENTS.md canonical + thin pointers).
  const canonical = path.join(repoRoot, 'AGENTS.md');
  if (!fs.existsSync(canonical) || opts.overwrite) {
    fs.writeFileSync(canonical, composeAgentsMd(profile));
    created.push('AGENTS.md');
  }
  const writtenAgents = [];
  for (const key of agents) {
    const rel = writeAgentPointer(repoRoot, key);
    if (rel) { writtenAgents.push(rel); created.push(rel); }
  }

  return {
    created: created.map((c) => path.relative(repoRoot, path.isAbsolute(c) ? c : path.join(repoRoot, c))),
    config,
    agents: writtenAgents
  };
}
